Load & check the data:

In [12]:
import pandas as pd
df_renee = pd.read_csv('pima-indians-diabetes.csv')
first_10_rows = df_renee.head(10)
print(first_10_rows)
# step of 2: Add the column names i.e. add a header record to the data frame
df_renee.columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'] 
print(df_renee.head(10))

    6  148  72  35    0  33.6  0.627  50  1
0   1   85  66  29    0  26.6  0.351  31  0
1   8  183  64   0    0  23.3  0.672  32  1
2   1   89  66  23   94  28.1  0.167  21  0
3   0  137  40  35  168  43.1  2.288  33  1
4   5  116  74   0    0  25.6  0.201  30  0
5   3   78  50  32   88  31.0  0.248  26  1
6  10  115   0   0    0  35.3  0.134  29  0
7   2  197  70  45  543  30.5  0.158  53  1
8   8  125  96   0    0   0.0  0.232  54  1
9   4  110  92   0    0  37.6  0.191  30  0
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   
5            3       78             50             32       88  31.0   
6           

Carryout some initial investigations:

In [13]:
# Check the names and types of columns.
print(df_renee.dtypes)
# Check the missing values.
print(df_renee.isnull().sum())
# Check the statistics of the numeric fields (mean, min, max, median, count,..etc.)
print(df_renee.describe())
# Check the categorical values, if any.
print(df_renee['Outcome'].value_counts())

###########In you written response write a paragraph explaining your findings about each column.###########
# Print out the total number of instances in each class
print(df_renee['Outcome'].value_counts())

##########and note into your report and explain your findings in terms of balanced and un-balanced classes.##########









Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64
       Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   767.000000  767.000000     767.000000     767.000000  767.000000   
mean      3.842243  120.859192      69.101695      20.517601   79.903520   
std       3.370877   31.978468      19.368155      15.954059  115.283105   
min       0.000000    0.000000       0.000000       0.000000    0.000000   

Pre-process and prepare the data for machine learning

In [14]:
# Prepare a standard scaler transformer to transform all the numeric values. 
from sklearn.preprocessing import StandardScaler
transformer_renee = StandardScaler()
# Split the features from the class.
X = df_renee.drop('Outcome', axis=1)
y = df_renee['Outcome']
# Split your data into train 70% train and 30% test, use 42 for the seed. Name the train/test dataframes as follows : X_train_firstname, X_test firstname, y_train firstname, y_test firstname
from sklearn.model_selection import train_test_split
X_train_renee, X_test_renee, y_train_renee, y_test_renee = train_test_split(X, y, test_size=0.3, random_state=42)
# Apply(fit, transform the transformer prepared in step 4 to the features i.e. X_train_firstname, X_test firstname, Name the transformer transformer_firstname, (Note: You might need to work on some transformation for the labels in order for the classifiers to work properly)
transformer_renee.fit(X_train_renee)
X_train_renee = transformer_renee.transform(X_train_renee)
X_test_renee = transformer_renee.transform(X_test_renee)

Exercise #1 :Hard voting 

In [15]:
# step #8: Define 5 classifiers & give them names of your choice, just add at the end _X, where X is the first letter of your last name. Details of classifiers are as follows:
# a. Logistic Regression set max_iter=1400
# b. Random Forest Classifier, use the defaults
# c. Support vector machines use the defaults
# d. Decision Tree Classifier set criterion="entropy" & max_depth =42
# e. Extra Trees Classifier, use the defaults
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
logistic_regression_v = LogisticRegression(max_iter=1400)
random_forest_v = RandomForestClassifier()
svc_v = SVC()
decision_tree_v = DecisionTreeClassifier(criterion='entropy', max_depth=42)
extra_trees_v = ExtraTreesClassifier()

# Define a voting classifier that contains all the above classifiers as estimators, set the voting to hard
from sklearn.ensemble import VotingClassifier
voting_classifier_v = VotingClassifier(estimators=[('lr', logistic_regression_v), ('rf', random_forest_v), ('svc', svc_v), ('dt', decision_tree_v), ('et', extra_trees_v)], voting='hard')
# Fit the training data to the voting classifier and predict the first three instances of test data
voting_classifier_v.fit(X_train_renee, y_train_renee)
y_pred_v = voting_classifier_v.predict(X_test_renee)
print(y_pred_v[:3])
# bu using a nested loop, Print out for each classifier (including the voting classifier) and for each instance the predicted and the actual values and note them in your written response.
for clf in (logistic_regression_v, random_forest_v, svc_v, decision_tree_v, extra_trees_v, voting_classifier_v):
    clf.fit(X_train_renee, y_train_renee)
    y_pred = clf.predict(X_test_renee)
    print(clf.__class__.__name__, y_pred[:3], y_test_renee[:3])

# Print out the accuracy score, classification report, and confusion matrix for each classifier and the voting classifier.
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
for clf in (logistic_regression_v, random_forest_v, svc_v, decision_tree_v, extra_trees_v, voting_classifier_v):
    clf.fit(X_train_renee, y_train_renee)
    y_pred = clf.predict(X_test_renee)
    print(clf.__class__.__name__)
    print(accuracy_score(y_test_renee, y_pred))
    print(classification_report(y_test_renee, y_pred))
    print(confusion_matrix(y_test_renee, y_pred))
    print('----------------------------------')

###########In your written response, analyze the results and draw some conclusions about the performance of the classifiers.###########

[0 0 0]
LogisticRegression [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
RandomForestClassifier [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
SVC [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
DecisionTreeClassifier [1 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
ExtraTreesClassifier [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
VotingClassifier [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
LogisticRegression
0.7922077922077922
              precision    recall  f1-score   support

           0       0.80      0.91      0.85       151
           1       0.77      0.57      0.66        80

    accuracy                           0.79       231
   macro avg       0.78      0.74      0.75       231
weighted avg       0.79      0.79      0.78       231

[[137  14]
 [ 34  46]]
----------------------------------
RandomForestClassifier
0.7619047619047619
              precision    recall  f1-scor

Exercise #2: Soft voting

In [16]:
# Repeat al the section Exercise #1 :Hard voting, except this step: "Define a voting classifier that contains all the above classifiers as estimators, set the voting to hard.", Note: You might need to change some classifiers defaults.
logistic_regression_v = LogisticRegression(max_iter=1400)
random_forest_v = RandomForestClassifier()
svc_v = SVC(probability=True)
decision_tree_v = DecisionTreeClassifier(criterion='entropy', max_depth=42)
extra_trees_v = ExtraTreesClassifier()
# Define a voting classifier that contains all the above classifiers as estimators, set the voting to soft
voting_classifier_v = VotingClassifier(estimators=[('lr', logistic_regression_v), ('rf', random_forest_v), ('svc', svc_v), ('dt', decision_tree_v), ('et', extra_trees_v)], voting='soft')
# Fit the training data to the voting classifier and predict the first three instances of test data
voting_classifier_v.fit(X_train_renee, y_train_renee)
y_pred_v = voting_classifier_v.predict(X_test_renee)
print(y_pred_v[:3])
# bu using a nested loop, Print out for each classifier (including the voting classifier) and for each instance the predicted and the actual values and note them in your written response.
for clf in (logistic_regression_v, random_forest_v, svc_v, decision_tree_v, extra_trees_v, voting_classifier_v):
    clf.fit(X_train_renee, y_train_renee)
    y_pred = clf.predict(X_test_renee)
    print(clf.__class__.__name__, y_pred[:3], y_test_renee[:3])

# Print out the accuracy score, classification report, and confusion matrix for each classifier and the voting classifier.
for clf in (logistic_regression_v, random_forest_v, svc_v, decision_tree_v, extra_trees_v, voting_classifier_v):
    clf.fit(X_train_renee, y_train_renee)
    y_pred = clf.predict(X_test_renee)
    print(clf.__class__.__name__)
    print(accuracy_score(y_test_renee, y_pred))
    print(classification_report(y_test_renee, y_pred))
    print(confusion_matrix(y_test_renee, y_pred))
    print('----------------------------------')
    


[0 0 0]
LogisticRegression [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
RandomForestClassifier [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
SVC [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
DecisionTreeClassifier [1 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
ExtraTreesClassifier [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
VotingClassifier [0 0 0] 667    0
324    0
623    0
Name: Outcome, dtype: int64
LogisticRegression
0.7922077922077922
              precision    recall  f1-score   support

           0       0.80      0.91      0.85       151
           1       0.77      0.57      0.66        80

    accuracy                           0.79       231
   macro avg       0.78      0.74      0.75       231
weighted avg       0.79      0.79      0.78       231

[[137  14]
 [ 34  46]]
----------------------------------
RandomForestClassifier
0.7489177489177489
              precision    recall  f1-scor

Exercise #3: Random forests & Extra Trees

In [17]:
# step #15:  Building on the previous classifiers you defined, create two different pipelines as follows:
#   a. Pipeline #1 : Name it pipeline1_firstname. The pipeline should have two steps, the first the transformer you prepared in step #4 and the second the Extra Trees Classifier you prepared in step 8.e.
#   b. Pipeline #2 : Name it pipeline1_firstname. The pipeline should have two steps, the first the transformer you prepared in step #4 and the second the Decision Tree Classifier you prepared in step 8.d
# this is the stept 4 : Prepare a standard scaler transformer to transform all the numeric values. Name the transformer transformer_firstname.
# this is the step 8.e : Define 5 classifiers & give them names of your choice, just add at the end _X, where X is the first letter of your last name. Details of classifiers are as follows:
# d. Decision Tree Classifier set criterion="entropy" & max_depth =42
# e. Extra Trees Classifier, use the defaults
from sklearn.pipeline import Pipeline
pipeline1_renee = Pipeline([('scaler', transformer_renee), ('et', extra_trees_v)])
pipeline2_renee = Pipeline([('scaler', transformer_renee), ('dt', decision_tree_v)])
# Fit the original data to both pipelines
pipeline1_renee.fit(X_train_renee, y_train_renee)
pipeline2_renee.fit(X_train_renee, y_train_renee)
# step # 17 : Carry out a 10 fold cross validation for both pipelines set shuffling to true and random_state to 42
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=10, shuffle=True, random_state=42)
scores_pipeline1 = cross_val_score(pipeline1_renee, X_train_renee, y_train_renee, cv=kf, scoring='accuracy', n_jobs=-1)
scores_pipeline2 = cross_val_score(pipeline2_renee, X_train_renee, y_train_renee, cv=kf, scoring='accuracy', n_jobs=-1)


# Printout the mean score evaluation for both pipelines, note the final results in your written response and advise which pipeline performed better
print(scores_pipeline1.mean())
print(scores_pipeline2.mean())
# Predict the test using both pipelines and printout the confusion matrix, precision, recall and accuracy scores and record the results in your written response. (Use a loop)
for pipeline in (pipeline1_renee, pipeline2_renee):
    pipeline.fit(X_train_renee, y_train_renee)
    y_pred = pipeline.predict(X_test_renee)
    print(pipeline)
    print(confusion_matrix(y_test_renee, y_pred))
    print(classification_report(y_test_renee, y_pred))
    print(accuracy_score(y_test_renee, y_pred))
    print('----------------------------------')

# step of 20: Compare the results and compare them against each other and against the accuracy scores you recorded during step #18, write some conclusions




0.7516072676450034
0.6919636617749825
Pipeline(steps=[('scaler', StandardScaler()), ('et', ExtraTreesClassifier())])
[[129  22]
 [ 35  45]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82       151
           1       0.67      0.56      0.61        80

    accuracy                           0.75       231
   macro avg       0.73      0.71      0.72       231
weighted avg       0.75      0.75      0.75       231

0.7532467532467533
----------------------------------
Pipeline(steps=[('scaler', StandardScaler()),
                ('dt',
                 DecisionTreeClassifier(criterion='entropy', max_depth=42))])
[[113  38]
 [ 29  51]]
              precision    recall  f1-score   support

           0       0.80      0.75      0.77       151
           1       0.57      0.64      0.60        80

    accuracy                           0.71       231
   macro avg       0.68      0.69      0.69       231
weighted avg       0.72      0.71    


Exercise #4: Extra Trees and Grid search

In [18]:
# Carryout a randomized grid search on the first Pipeline you defined in step #15: The randomized grid search should investigate the use of different values for the following two parameters:
# a.	The number of trees in the forest. Use a distribution between the values of 10 trees and 3000 trees with a step of 20.
# b.	The maximum depth of the tree.  Use a distribution between the values of 1 max depth and 1000 max_depth with a step of 2.
# Choose appropriate names for both your grid search parameter objects that end with_05.
from sklearn.model_selection import RandomizedSearchCV
import numpy as np
n_estimators_05 = np.arange(10, 3000, 20)
max_depth_05 = np.arange(1, 1000, 2)
param_distributions_05 = {'et__n_estimators': n_estimators_05, 'et__max_depth': max_depth_05}
# 22.	Fit your training data to the randomized gird search object.
randomized_search_05 = RandomizedSearchCV(pipeline1_renee, param_distributions_05, n_iter=100, cv=10, scoring='accuracy', n_jobs=-1, random_state=42)
randomized_search_05.fit(X_train_renee, y_train_renee)
# 23.	Print out the best parameters and accuracy score for randomized grid search and record them in your written response and comment on these results. For example, compare the accuracy score to the one you obtained in step # 17 and compare the parameters suggested by the randomized grid search to the ones you used in the classifier setup i.e. step #8. list any conclusions you noticed.






RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                             ('et', ExtraTreesClassifier())]),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'et__max_depth': array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 1...
       1550, 1570, 1590, 1610, 1630, 1650, 1670, 1690, 1710, 1730, 1750,
       1770, 1790, 1810, 1830, 1850, 1870, 1890, 1910, 1930, 1950, 1970,
       1990, 2010, 2030, 2050, 2070, 2090, 2110, 2130, 2150, 2170, 2190,
       2210, 2230, 2250, 2270, 2290, 2310, 2330, 2350, 2370, 2390, 2410,
       2430, 2450, 2470, 2490, 2510, 2530, 2550, 2570, 2590, 2610, 2630,
       2650, 2670, 2690, 2710, 2730, 2750, 2770, 2790, 2810, 2830, 2850,
       2870, 2890, 2910, 2930, 2950, 2970, 2990])},
                   random_state=42, scoring='accuracy')

In [20]:
# 24.	Use the fine-tuned model identified during the randomized grid search i.e the best estimator saved in the randomized grid search object to predict the test data and note the results it in your written response.
y_pred_05 = randomized_search_05.best_estimator_.predict(X_test_renee)
print(confusion_matrix(y_test_renee, y_pred_05))
print(classification_report(y_test_renee, y_pred_05))
print(accuracy_score(y_test_renee, y_pred_05))



[[127  24]
 [ 33  47]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82       151
           1       0.66      0.59      0.62        80

    accuracy                           0.75       231
   macro avg       0.73      0.71      0.72       231
weighted avg       0.75      0.75      0.75       231

0.7532467532467533
